### PR TITLE
fix Travis setup

### PR DESCRIPTION
**Pull request by duck-rh**
Please withdraw PR #10

### CODE REVIEW

**Comment by duck-rh** [comment]
problems with long build, see https://github.com/travis-ci/travis-ci/issues/6591

**Comment by mscherer** [comment]
So, while I agree we need to have CI, I kinda propose to not block on having it for now, so can we revisit the #10 PR ?

**Comment by duck-rh** [comment]
Ok.
We need to keep this branch and maybe keep this PR as a reminder or something to avoid forgeting about it.

**Comment by mscherer** [comment]
You can just put all the stuff in a comment, so we do not forget about it.

**Comment by duck-rh** [comment]
invalidated by #12

**Pull request closed without merging**
