### PR TITLE
Remove old travis config

### PR DESCRIPTION
**Pull request by mscherer**
As the role is not working on ubuntu and I do not want to
spend time on itfor that, let's remove the test who never worked.

### CODE REVIEW

**Comment by duck-rh** [comment]
I disagree.
Last time we fixed packaging issues, why not go on?
I just checked the error and see nothing difficult to fix. Maybe another step will prove me wrong but it seems you're giving up very very fast.
Please keep this on hold while I work on proposing a fix.

**Comment by mscherer** [comment]
The problem I have is that:
- the test do requires a external repository 
- that this external repository is building fine on travis at all time.

I kinda see that as being risky, since we would inherit all the issues of the upstream site we will use, and all the issue with gems that do appear from time to time. I am sure this is easy to make it work now, but I suspect this will be annoying us in the future because "gems".

**Comment by duck-rh** [comment]
127.0.0.1                  : ok=12   changed=4    unreachable=0    failed=0  
on the last test, and after a fix of the chosen repo, will do a PR then

**Comment by duck-rh** [comment]
It's using the MM template repo, which is nice to test too, small enough, and should not have that much problems as it is just an example

**Comment by duck-rh** [comment]
done in #12

**Pull request closed without merging**
