### PR TITLE
fix conditional in PR#19

### PR DESCRIPTION
**Pull request by duck-rh**
I'm not used to the original syntax, so I used one I think is safe.

I tested this on the OSCI web builder successfully.

### CODE REVIEW

**Comment by duck-rh** [comment]
I reviewed this PR too fast, my bad.

**Comment by mscherer** [comment]
The correct way should be indeed to use '{%' and not '{{'

**Comment by duck-rh** [comment]
I should have though about it indeed.

Do you prefer this syntax over ternary()? (it avoids manual boolean conversion) is there a behavioral difference or advice on which is better in which case?

Then I can update the PR.

**Comment by mscherer** [comment]
I tend to prefer that syntax, yes. 

It is quite easy to forget the 'bool' before the ternary filter, and that make harder to notice there is something wrong (because it do not break in a very obvious and clear way).

**Comment by duck-rh** [comment]
So be it. Here is the fixed version with the preferred syntax.

**Pull request merged**
