### PR TITLE
generate SSH config

### PR DESCRIPTION
**Pull request by duck-rh**

### CODE REVIEW

**Comment by duck-rh** [comment]
So, this fails because we need Ansible 2.3 for named block feature. I made the changes for the test container but due to Gitlab's API timeout I can't get the Quay.io image rebuilt at the moment.

**Comment by mscherer** [comment]
So, can you describe a bit more what is the problem to be fixed ?

**Comment by duck-rh** [comment]
The previous SSH config file on the builders were not managed via Ansible but created manually.

Also the way the role is written seem to indicate handling multiple builds was intended, so I made sure we're matching the right key even if we deploy a sub-part of the website on the same machine (we just need another account).

**Comment by mscherer** [comment]
That's fine by me, but what about the ci run, should we merge it nonetheless ?

**Comment by duck-rh** [comment]
That's a problem we're going to have more and more unfortunately and we're certainly not going to stick to an old Ansible version if we need the features.

I tried again to use Quay+GL and it still timeout.t has been moths now and noone cares so I guess we should find some time (not sure when) to continue work on this.

In the meanwhile the only thing I can suggest for this PR (not sure the other ones would not have similar problems) is to comment the name on the block.

**Comment by mscherer** [comment]
Well, I am ok to merge the PR, but the interface do not let me. So we can disable the requirement of "ci must pass" for now ?

**Pull request merged**
